In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn import preprocessing
from sklearn.metrics import accuracy_score

In [2]:
random_state = 8
data = pd.read_csv('EEG_Eye_State.csv')
print(data.shape)
print(data)

(14980, 15)
           AF3       F7       F3      FC5       T7       P7       O1       O2  \
0      4329.23  4009.23  4289.23  4148.21  4350.26  4586.15  4096.92  4641.03   
1      4324.62  4004.62  4293.85  4148.72  4342.05  4586.67  4097.44  4638.97   
2      4327.69  4006.67  4295.38  4156.41  4336.92  4583.59  4096.92  4630.26   
3      4328.72  4011.79  4296.41  4155.90  4343.59  4582.56  4097.44  4630.77   
4      4326.15  4011.79  4292.31  4151.28  4347.69  4586.67  4095.90  4627.69   
...        ...      ...      ...      ...      ...      ...      ...      ...   
14975  4281.03  3990.26  4245.64  4116.92  4333.85  4614.36  4074.87  4625.64   
14976  4276.92  3991.79  4245.13  4110.77  4332.82  4615.38  4073.33  4621.54   
14977  4277.44  3990.77  4246.67  4113.85  4333.33  4615.38  4072.82  4623.59   
14978  4284.62  3991.79  4251.28  4122.05  4334.36  4616.41  4080.51  4628.72   
14979  4287.69  3997.44  4260.00  4121.03  4333.33  4616.41  4088.72  4638.46   

            P8 

In [3]:
X = data.loc[:,data.columns !='Eye_detection']
y = data['Eye_detection']
print(y)

0        0
1        0
2        0
3        0
4        0
        ..
14975    1
14976    1
14977    1
14978    1
14979    1
Name: Eye_detection, Length: 14980, dtype: int64


In [4]:
normalized_X = preprocessing.normalize(X, axis=0)
print(normalized_X)
print(normalized_X.shape)

[[0.00709008 0.00816878 0.00821827 ... 0.00817247 0.00793945 0.00487585]
 [0.00708253 0.00815939 0.00822712 ... 0.00817052 0.00793417 0.00486503]
 [0.00708756 0.00816357 0.00823005 ... 0.00817541 0.00792715 0.00487072]
 ...
 [0.00700526 0.00813117 0.00813672 ... 0.0081294  0.0078639  0.00481553]
 [0.00701702 0.00813325 0.00814556 ... 0.00814702 0.00787182 0.00482804]
 [0.00702205 0.00814476 0.00816226 ... 0.00816073 0.00787445 0.00482804]]
(14980, 14)


In [5]:
np.linalg.norm(normalized_X[:,0])

0.9999999999999954

In [11]:
# Split into train and test data 
X_train, X_test, y_train, y_test = train_test_split(normalized_X, y, test_size = 0.2, random_state = random_state)
# Train a multi-layer perceptron
clf0 = MLPClassifier(hidden_layer_sizes=(100,100),random_state=random_state, verbose=False, max_iter=1000)
clf0.fit(X_train, y_train)
# Predict accuracy of classifier
y_pred = clf0.predict(X_test)
acc = accuracy_score(y_pred, y_test)
print('Accuracy on normalized : ', acc*100)


Accuracy on normalized :  55.57409879839786


In [12]:
# Split into train and test data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = random_state)
# Train a multi-layer perceptron
clf0 = MLPClassifier(hidden_layer_sizes=(100,100),random_state=random_state, verbose=False, max_iter=1000)
clf0.fit(X_train, y_train)
# Predict accuracy of classifier
y_pred = clf0.predict(X_test)
acc = accuracy_score(y_pred, y_test)
print('Accuracy on raw : ', acc*100)


Accuracy on raw :  44.45927903871829


In [13]:
## Feature scalig

In [14]:
scaled_X = preprocessing.scale(X)
print(scaled_X[:,0].shape)
np.mean(scaled_X[:,0])

(14980,)


-1.328117263102991e-16

In [15]:
# Split into train and test data 
X_train, X_test, y_train, y_test = train_test_split(scaled_X, y, test_size = 0.2, random_state = random_state)
# Train a multi-layer perceptron
clf0 = MLPClassifier(hidden_layer_sizes=(100,100),random_state=random_state, verbose=False, max_iter=1000)
clf0.fit(X_train, y_train)
# Predict accuracy of classifier
y_pred = clf0.predict(X_test)
acc = accuracy_score(y_pred, y_test)
print('Accuracy on scaled : ', acc*100)


Accuracy on scaled :  90.82109479305741
